import { router } from 'expo-router';
import { useEffect, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { ActionTile, Icon } from '../../src/components/FieldUI';
import { loadMembership } from '../../src/lib/membership';
import type { Membership } from '../../src/types/app';
import { colors, spacing, typography } from '../../src/theme';

export default function ManagementScreen() {
  const [m, setM] = useState<Membership | null>(null);
  useEffect(() => { loadMembership().then(setM); }, []);
  const canManage = m?.roles.some((r) => r === 'owner' || r === 'operations_manager');
  return <ScrollView contentContainerStyle={styles.root} showsVerticalScrollIndicator={false}><View style={styles.header}><View><Text style={styles.eyebrow}>CONTROL ROOM</Text><Text style={styles.title}>Management center</Text></View><View style={styles.headerIcon}><Icon name="settings-outline" color={colors.teal} size={22} /></View></View><Text style={styles.intro}>Keep people, coverage, and field operations aligned from one place.</Text>{canManage ? <><Pressable style={({ pressed }) => [styles.invite, pressed && styles.pressed]} onPress={() => router.push('/invite-employee')}><View style={styles.inviteIcon}><Icon name="person-add-outline" color={colors.background} size={20} /></View><View style={styles.inviteCopy}><Text style={styles.inviteTitle}>Invite an employee</Text><Text style={styles.inviteText}>Create access for a new technician</Text></View><Icon name="arrow-forward" color={colors.background} size={20} /></Pressable><Text style={styles.sectionLabel}>Operations directory</Text><View style={styles.tiles}><ActionTile icon="people-outline" title="Employees" subtitle="Team roster and roles" /><ActionTile icon="git-network-outline" title="Crews" subtitle="Group field coverage" /><ActionTile icon="calendar-outline" title="Availability" subtitle="Schedules and time off" /><ActionTile icon="ribbon-outline" title="Skills" subtitle="Certifications and capabilities" /><ActionTile icon="navigate-outline" title="Dispatch" subtitle="Assignments and routing" /><ActionTile icon="business-outline" title="Properties & geofences" subtitle="Sites and operating zones" /><ActionTile icon="lock-closed-outline" title="Permissions" subtitle="Role access controls" /><ActionTile icon="mail-outline" title="Invitations" subtitle="Pending access requests" /></View></> : <View style={styles.locked}><Icon name="lock-closed-outline" color={colors.amber} size={24} /><Text style={styles.lockedTitle}>Management access required</Text><Text style={styles.lockedText}>Your current role does not include operations management controls.</Text></View>}</ScrollView>;
}
const styles = StyleSheet.create({ root: { backgroundColor: colors.background, gap: spacing.lg, padding: spacing.lg, paddingBottom: 110 }, header: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', paddingTop: spacing.sm }, eyebrow: { color: colors.teal, fontSize: 11, fontWeight: '800', letterSpacing: 1.2 }, title: { color: colors.text, ...typography.title, marginTop: 4 }, headerIcon: { alignItems: 'center', backgroundColor: colors.tealDeep, borderRadius: 999, height: 44, justifyContent: 'center', width: 44 }, intro: { color: colors.muted, fontSize: 14, lineHeight: 21, marginTop: -spacing.sm }, invite: { alignItems: 'center', backgroundColor: colors.teal, borderRadius: 16, flexDirection: 'row', minHeight: 76, padding: spacing.md }, inviteIcon: { alignItems: 'center', backgroundColor: '#FFFFFF55', borderRadius: 11, height: 42, justifyContent: 'center', width: 42 }, inviteCopy: { flex: 1, marginLeft: spacing.md }, inviteTitle: { color: colors.background, fontSize: 15, fontWeight: '800' }, inviteText: { color: '#0B1117AA', fontSize: 12, marginTop: 3 }, sectionLabel: { color: colors.muted, fontSize: 12, fontWeight: '800', letterSpacing: 0.8, marginBottom: -spacing.sm, textTransform: 'uppercase' }, tiles: { gap: spacing.sm }, locked: { alignItems: 'center', backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 18, borderWidth: 1, padding: spacing.xxl }, lockedTitle: { color: colors.text, fontSize: 16, fontWeight: '800', marginTop: spacing.md }, lockedText: { color: colors.muted, fontSize: 13, lineHeight: 19, marginTop: 6, textAlign: 'center' }, pressed: { opacity: 0.78 } });
