import { router } from 'expo-router';
import { useEffect, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Badge, Card, EmptyState, Icon } from '../../src/components/FieldUI';
import { LoadingScreen } from '../../src/components/LoadingScreen';
import { loadMembership } from '../../src/lib/membership';
import { formatStatus, loadEmployeeDirectory } from '../../src/lib/employeeData';
import { colors, spacing, typography } from '../../src/theme';
import type { Membership } from '../../src/types/app';

type SkillsData = Awaited<ReturnType<typeof loadEmployeeDirectory>>;
const canManage = (membership: Membership | null) => Boolean(membership?.roles.some((role) => role === 'owner' || role === 'operations_manager'));

export default function SkillsScreen() {
  const [membership, setMembership] = useState<Membership | null>(null);
  const [data, setData] = useState<SkillsData | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  useEffect(() => { (async () => { try { const current = await loadMembership(); setMembership(current); if (current && canManage(current)) setData(await loadEmployeeDirectory(current.companyId)); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Could not load skills.'); } finally { setLoading(false); } })(); }, []);
  if (loading) return <LoadingScreen label="Loading skills setup..." />;
  if (!canManage(membership)) return <Message title="Management access required" message="Your current role does not include skills management." />;
  if (error) return <Message title="Skills unavailable" message={error} />;
  const grouped = (data?.skills ?? []).reduce<Record<string, SkillsData['skills']>>((groups, skill) => { const category = skill.category || 'Uncategorized'; (groups[category] ||= []).push(skill); return groups; }, {});
  return <ScrollView contentContainerStyle={styles.root} showsVerticalScrollIndicator={false}><View style={styles.topbar}><Pressable onPress={() => router.back()} style={styles.back}><Icon name="arrow-back" color={colors.text} size={21} /></Pressable><View style={styles.headerCopy}><Text style={styles.eyebrow}>PEOPLE OPERATIONS</Text><Text style={styles.title}>Skills setup</Text></View><View style={styles.headerIcon}><Icon name="ribbon-outline" color={colors.teal} size={21} /></View></View><View style={styles.intro}><Text style={styles.introTitle}>Capabilities library</Text><Text style={styles.introText}>Keep the skills used for floating coverage and dispatch decisions in one place.</Text></View><Pressable disabled style={styles.addButton}><Icon name="add" color={colors.background} size={20} /><Text style={styles.addText}>Add skill</Text><Badge label="Setup required" tone="amber" /></Pressable>{data?.skills.length ? Object.entries(grouped).map(([category, skills]) => <View key={category} style={styles.group}><Text style={styles.groupTitle}>{category}</Text>{skills?.map((skill) => <Card key={skill.id} style={styles.skill}><View style={styles.skillTop}><Text style={styles.skillName}>{skill.name}</Text><Badge label={skill.active ? 'Active' : 'Inactive'} tone={skill.active ? 'teal' : 'neutral'} /></View>{skill.description && <Text style={styles.description}>{skill.description}</Text>}</Card>)}</View>) : <EmptyState icon="ribbon-outline" title="Skills are not configured" message="Company skills must be configured before employee skill assignments can be made." />}<Card style={styles.setupNote}><Icon name="information-circle-outline" color={colors.blue} size={21} /><View style={styles.noteCopy}><Text style={styles.noteTitle}>Skill setup is not available yet</Text><Text style={styles.noteText}>The Add skill action is disabled until a safe, RLS-backed management write is available. Nothing has been inserted automatically.</Text></View></Card></ScrollView>;
}
function Message({ title, message }: { title: string; message: string }) { return <View style={styles.message}><Icon name="alert-circle-outline" color={colors.amber} size={25} /><Text style={styles.messageTitle}>{title}</Text><Text style={styles.messageText}>{message}</Text><Pressable onPress={() => router.back()} style={styles.backButton}><Text style={styles.backText}>Back</Text></Pressable></View>; }
const styles = StyleSheet.create({ root: { backgroundColor: colors.background, flexGrow: 1, padding: spacing.lg, paddingBottom: 110 }, topbar: { alignItems: 'center', flexDirection: 'row', paddingTop: spacing.sm }, back: { alignItems: 'center', backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 12, borderWidth: 1, height: 42, justifyContent: 'center', width: 42 }, headerCopy: { flex: 1, marginLeft: spacing.md }, eyebrow: { color: colors.teal, fontSize: 11, fontWeight: '800', letterSpacing: 1.2 }, title: { color: colors.text, ...typography.title, marginTop: 3 }, headerIcon: { alignItems: 'center', backgroundColor: colors.tealDeep, borderRadius: 999, height: 44, justifyContent: 'center', width: 44 }, intro: { marginTop: spacing.xxl }, introTitle: { color: colors.text, ...typography.heading }, introText: { color: colors.muted, fontSize: 14, lineHeight: 21, marginTop: spacing.xs }, addButton: { alignItems: 'center', backgroundColor: colors.teal, borderRadius: 14, flexDirection: 'row', gap: spacing.sm, marginVertical: spacing.xl, minHeight: 54, opacity: 0.52, paddingHorizontal: spacing.md }, addText: { color: colors.background, flex: 1, fontSize: 15, fontWeight: '800' }, group: { marginBottom: spacing.lg }, groupTitle: { color: colors.muted, fontSize: 12, fontWeight: '800', letterSpacing: 0.8, marginBottom: spacing.sm, textTransform: 'uppercase' }, skill: { marginBottom: spacing.sm, padding: spacing.md }, skillTop: { alignItems: 'center', flexDirection: 'row' }, skillName: { color: colors.text, flex: 1, fontSize: 15, fontWeight: '800' }, description: { color: colors.muted, fontSize: 13, lineHeight: 19, marginTop: spacing.sm }, setupNote: { alignItems: 'flex-start', flexDirection: 'row', padding: spacing.md }, noteCopy: { flex: 1, marginLeft: spacing.md }, noteTitle: { color: colors.text, fontSize: 14, fontWeight: '800' }, noteText: { color: colors.muted, fontSize: 12, lineHeight: 18, marginTop: 4 }, message: { alignItems: 'center', backgroundColor: colors.background, flex: 1, justifyContent: 'center', padding: spacing.xl }, messageTitle: { color: colors.text, fontSize: 18, fontWeight: '800', marginTop: spacing.lg }, messageText: { color: colors.muted, fontSize: 14, lineHeight: 21, marginTop: spacing.sm, textAlign: 'center' }, backButton: { backgroundColor: colors.teal, borderRadius: 14, marginTop: spacing.xl, paddingHorizontal: spacing.xl, paddingVertical: spacing.md }, backText: { color: colors.background, fontWeight: '800' },
});
