import { useEffect, useState } from 'react';
import { FlatList, StyleSheet, Text, View } from 'react-native';
import { Badge, Card, EmptyState, Icon, SectionHeader } from '../../src/components/FieldUI';
import { supabase } from '../../src/lib/supabase';
import { colors, spacing, typography } from '../../src/theme';

type Turnover = { id: string; status: string; target_completion_at: string | null; unit_id: string };
export default function TurnoversScreen() {
  const [rows, setRows] = useState<Turnover[]>([]);
  useEffect(() => { supabase.from('turnovers').select('id,status,target_completion_at,unit_id').order('created_at', { ascending: false }).then(({ data }) => setRows((data ?? []) as Turnover[])); }, []);
  return <FlatList contentContainerStyle={styles.root} data={rows} keyExtractor={(x) => x.id} showsVerticalScrollIndicator={false} ListHeaderComponent={<><View style={styles.header}><View><Text style={styles.eyebrow}>OPERATIONS BOARD</Text><Text style={styles.heading}>Turnovers</Text></View><View style={styles.count}><Text style={styles.countValue}>{rows.length}</Text><Text style={styles.countLabel}>ACTIVE</Text></View></View><SectionHeader title="Readiness pipeline" /></>} ListEmptyComponent={<EmptyState icon="sync-outline" title="No active turnovers" message="When units enter turnover, their phase, progress, and blockers will be tracked here." />} renderItem={({ item }) => <TurnoverCard item={item} />} />;
}
function TurnoverCard({ item }: { item: Turnover }) { const status = item.status.replaceAll('_', ' '); const complete = ['completed', 'ready', 'complete'].some((value) => item.status.toLowerCase().includes(value)); const progress = complete ? 100 : item.status.toLowerCase().includes('inspection') ? 70 : item.status.toLowerCase().includes('clean') ? 45 : 20; const tone = item.status.toLowerCase().includes('block') ? 'red' : complete ? 'teal' : 'amber'; return <Card style={styles.card}><View style={styles.cardTop}><Badge label={status} tone={tone} /><Text style={styles.date}>{item.target_completion_at ? new Date(item.target_completion_at).toLocaleDateString() : 'Target date pending'}</Text></View><Text style={styles.title}>Unit {item.unit_id.slice(0, 8)}…</Text><View style={styles.meta}><Icon name="business-outline" color={colors.subtle} size={15} /><Text style={styles.metaText}>Property details pending</Text></View><View style={styles.progressRow}><Text style={styles.progressLabel}>Readiness</Text><Text style={styles.progressValue}>{progress}%</Text></View><View style={styles.progressTrack}><View style={[styles.progressFill, { width: `${progress}%` }]} /></View><View style={styles.footer}><Text style={styles.phase}>{complete ? 'Ready for handoff' : 'In progress'}</Text>{item.status.toLowerCase().includes('block') && <View style={styles.blocker}><Icon name="alert-circle" color={colors.red} size={14} /><Text style={styles.blockerText}>Blocker</Text></View>}</View></Card>; }
const styles = StyleSheet.create({ root: { backgroundColor: colors.background, flexGrow: 1, padding: spacing.lg, paddingBottom: 110 }, header: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginBottom: spacing.lg, paddingTop: spacing.sm }, eyebrow: { color: colors.teal, fontSize: 11, fontWeight: '800', letterSpacing: 1.2 }, heading: { color: colors.text, ...typography.title, marginTop: 4 }, count: { alignItems: 'flex-end' }, countValue: { color: colors.text, fontSize: 26, fontWeight: '800' }, countLabel: { color: colors.subtle, fontSize: 10, fontWeight: '800', letterSpacing: 1 }, card: { marginBottom: spacing.sm, padding: spacing.md }, cardTop: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' }, date: { color: colors.muted, fontSize: 12 }, title: { color: colors.text, fontSize: 18, fontWeight: '800', marginTop: spacing.md }, meta: { alignItems: 'center', flexDirection: 'row', marginTop: 7 }, metaText: { color: colors.muted, fontSize: 13, marginLeft: 7 }, progressRow: { flexDirection: 'row', justifyContent: 'space-between', marginTop: spacing.lg }, progressLabel: { color: colors.muted, fontSize: 12, fontWeight: '700' }, progressValue: { color: colors.teal, fontSize: 12, fontWeight: '800' }, progressTrack: { backgroundColor: colors.surfaceSoft, borderRadius: 99, height: 7, marginTop: 8, overflow: 'hidden' }, progressFill: { backgroundColor: colors.teal, borderRadius: 99, height: 7 }, footer: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginTop: spacing.md }, phase: { color: colors.muted, fontSize: 12, fontWeight: '700', textTransform: 'capitalize' }, blocker: { alignItems: 'center', flexDirection: 'row' }, blockerText: { color: colors.red, fontSize: 12, fontWeight: '800', marginLeft: 5 } });
