import { useEffect, useMemo, useState } from 'react';
import { FlatList, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { Badge, Card, EmptyState, Icon, SectionHeader } from '../../src/components/FieldUI';
import { supabase } from '../../src/lib/supabase';
import { colors, spacing, typography } from '../../src/theme';

type Row = { id: string; title: string; status: string; priority: string; due_at: string | null };
export default function WorkOrdersScreen() {
  const [rows, setRows] = useState<Row[]>([]);
  const [query, setQuery] = useState('');
  const [filter, setFilter] = useState<'all' | 'urgent' | 'open'>('all');
  useEffect(() => { supabase.from('work_orders').select('id,title,status,priority,due_at').order('created_at', { ascending: false }).then(({ data }) => setRows((data ?? []) as Row[])); }, []);
  const visibleRows = useMemo(() => rows.filter((item) => `${item.title} ${item.status} ${item.priority}`.toLowerCase().includes(query.toLowerCase()) && (filter === 'all' || (filter === 'urgent' ? ['urgent', 'high'].includes(item.priority.toLowerCase()) : !['completed', 'closed'].includes(item.status.toLowerCase())))), [filter, query, rows]);
  return <FlatList contentContainerStyle={styles.root} data={visibleRows} keyExtractor={(x) => x.id} showsVerticalScrollIndicator={false} ListHeaderComponent={<><View style={styles.header}><View><Text style={styles.eyebrow}>FIELD QUEUE</Text><Text style={styles.heading}>Work orders</Text></View><View style={styles.count}><Text style={styles.countValue}>{rows.length}</Text><Text style={styles.countLabel}>TOTAL</Text></View></View><View style={styles.search}><Icon name="search-outline" color={colors.subtle} size={19} /><TextInput placeholder="Search work orders" placeholderTextColor={colors.subtle} value={query} onChangeText={setQuery} style={styles.searchInput} /></View><View style={styles.filters}>{(['all', 'urgent', 'open'] as const).map((value) => <Pressable key={value} onPress={() => setFilter(value)} style={[styles.filter, filter === value && styles.filterActive]}><Text style={[styles.filterText, filter === value && styles.filterTextActive]}>{value === 'all' ? 'All orders' : value === 'urgent' ? 'Priority' : 'Open'}</Text></Pressable>)}</View><SectionHeader title="Latest activity" /></>} ListEmptyComponent={rows.length ? <EmptyState icon="search-outline" title="No matching orders" message="Try a different search or filter." /> : <EmptyState icon="construct-outline" title="Queue is clear" message="New work orders will appear here as they are assigned." />} renderItem={({ item }) => <WorkOrderCard item={item} />} />;
}
function WorkOrderCard({ item }: { item: Row }) { const priority = item.priority.toLowerCase(); const status = item.status.replaceAll('_', ' '); const tone = priority === 'urgent' || priority === 'high' ? 'red' : priority === 'medium' ? 'amber' : 'blue'; return <Card style={styles.orderCard}><View style={styles.orderTop}><Badge label={item.priority} tone={tone} /><Text style={styles.status}>{status}</Text></View><Text style={styles.orderTitle}>{item.title}</Text><View style={styles.orderMeta}><View style={styles.meta}><Icon name="business-outline" size={15} color={colors.subtle} /><Text style={styles.metaText}>Property / unit pending</Text></View><View style={styles.meta}><Icon name="person-outline" size={15} color={colors.subtle} /><Text style={styles.metaText}>Assignment pending</Text></View></View><View style={styles.due}><Icon name="time-outline" size={15} color={item.due_at ? colors.amber : colors.subtle} /><Text style={styles.dueText}>{item.due_at ? `Due ${new Date(item.due_at).toLocaleDateString()}` : 'Due date not set'}</Text></View></Card>; }
const styles = StyleSheet.create({ root: { backgroundColor: colors.background, flexGrow: 1, padding: spacing.lg, paddingBottom: 110 }, header: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginBottom: spacing.lg, paddingTop: spacing.sm }, eyebrow: { color: colors.teal, fontSize: 11, fontWeight: '800', letterSpacing: 1.2 }, heading: { color: colors.text, ...typography.title, marginTop: 4 }, count: { alignItems: 'flex-end' }, countValue: { color: colors.text, fontSize: 26, fontWeight: '800' }, countLabel: { color: colors.subtle, fontSize: 10, fontWeight: '800', letterSpacing: 1 }, search: { alignItems: 'center', backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 14, borderWidth: 1, flexDirection: 'row', minHeight: 52, paddingHorizontal: spacing.md }, searchInput: { color: colors.text, flex: 1, fontSize: 15, marginLeft: spacing.sm }, filters: { flexDirection: 'row', gap: spacing.sm, marginVertical: spacing.lg }, filter: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 999, borderWidth: 1, paddingHorizontal: 14, paddingVertical: 9 }, filterActive: { backgroundColor: colors.tealDeep, borderColor: colors.teal }, filterText: { color: colors.muted, fontSize: 12, fontWeight: '800' }, filterTextActive: { color: colors.teal }, orderCard: { marginBottom: spacing.sm, padding: spacing.md }, orderTop: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' }, status: { color: colors.muted, fontSize: 12, fontWeight: '700', textTransform: 'capitalize' }, orderTitle: { color: colors.text, fontSize: 17, fontWeight: '800', marginTop: spacing.md }, orderMeta: { gap: spacing.sm, marginTop: spacing.md }, meta: { alignItems: 'center', flexDirection: 'row' }, metaText: { color: colors.muted, fontSize: 13, marginLeft: 7 }, due: { alignItems: 'center', borderTopColor: colors.border, borderTopWidth: 1, flexDirection: 'row', marginTop: spacing.md, paddingTop: spacing.md }, dueText: { color: colors.muted, fontSize: 12, marginLeft: 7 }, });
