import Ionicons from '@expo/vector-icons/Ionicons';
import type { ComponentProps, ReactNode } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { colors, shadow, spacing, typography } from '../theme';

type IconName = ComponentProps<typeof Ionicons>['name'];
export function Icon({ name, size = 20, color = colors.muted }: { name: IconName; size?: number; color?: string }) { return <Ionicons name={name} size={size} color={color} />; }
export function Card({ children, style }: { children: ReactNode; style?: object }) { return <View style={[styles.card, style]}>{children}</View>; }
export function Badge({ label, tone = 'neutral' }: { label: string; tone?: 'neutral' | 'teal' | 'blue' | 'amber' | 'red' }) {
  const toneStyles = { neutral: styles.badgeNeutral, teal: styles.badgeTeal, blue: styles.badgeBlue, amber: styles.badgeAmber, red: styles.badgeRed };
  const textStyles = { neutral: styles.neutralText, teal: styles.badgeTealText, blue: styles.badgeBlueText, amber: styles.badgeAmberText, red: styles.badgeRedText };
  return <View style={[styles.badge, toneStyles[tone]]}><Text style={[styles.badgeText, textStyles[tone]]}>{label}</Text></View>;
}
export function SectionHeader({ title, action, onAction }: { title: string; action?: string; onAction?: () => void }) { return <View style={styles.sectionHeader}><Text style={styles.sectionTitle}>{title}</Text>{action && <Pressable onPress={onAction} hitSlop={8}><Text style={styles.sectionAction}>{action}</Text></Pressable>}</View>; }
export function MetricCard({ label, value, icon, tone = 'teal' }: { label: string; value: string; icon: IconName; tone?: 'teal' | 'blue' | 'amber' | 'red' }) { const tint = { teal: colors.teal, blue: colors.blue, amber: colors.amber, red: colors.red }[tone]; return <Card style={styles.metric}><View style={[styles.metricIcon, { backgroundColor: `${tint}20` }]}><Icon name={icon} color={tint} size={17} /></View><Text style={styles.metricValue}>{value}</Text><Text style={styles.metricLabel}>{label}</Text></Card>; }
export function EmptyState({ icon, title, message }: { icon: IconName; title: string; message: string }) { return <Card style={styles.empty}><View style={styles.emptyIcon}><Icon name={icon} color={colors.teal} size={22} /></View><Text style={styles.emptyTitle}>{title}</Text><Text style={styles.emptyMessage}>{message}</Text></Card>; }
export function ActionTile({ icon, title, subtitle, onPress }: { icon: IconName; title: string; subtitle: string; onPress?: () => void }) { return <Pressable onPress={onPress} style={({ pressed }) => [styles.actionTile, pressed && styles.pressed]}><View style={styles.actionIcon}><Icon name={icon} color={colors.teal} size={19} /></View><View style={styles.actionCopy}><Text style={styles.actionTitle}>{title}</Text><Text style={styles.actionSubtitle}>{subtitle}</Text></View><Icon name="chevron-forward" color={colors.subtle} size={18} /></Pressable>; }

const styles = StyleSheet.create({
  card: { backgroundColor: colors.surface, borderColor: colors.border, borderWidth: 1, borderRadius: 18, padding: spacing.lg, ...shadow },
  badge: { alignSelf: 'flex-start', borderRadius: 999, paddingHorizontal: 9, paddingVertical: 5 }, badgeText: { fontSize: 11, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 0.5 }, badgeNeutral: { backgroundColor: colors.surfaceSoft }, badgeTeal: { backgroundColor: colors.tealDeep }, badgeBlue: { backgroundColor: colors.blueDeep }, badgeAmber: { backgroundColor: colors.amberDeep }, badgeRed: { backgroundColor: colors.redDeep }, neutralText: { color: colors.muted }, badgeTealText: { color: colors.teal }, badgeBlueText: { color: colors.blue }, badgeAmberText: { color: colors.amber }, badgeRedText: { color: colors.red },
  sectionHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginBottom: spacing.md }, sectionTitle: { color: colors.text, ...typography.heading }, sectionAction: { color: colors.teal, fontSize: 13, fontWeight: '800' }, metric: { flex: 1, minHeight: 120, padding: spacing.md }, metricIcon: { alignItems: 'center', borderRadius: 10, height: 32, justifyContent: 'center', width: 32 }, metricValue: { color: colors.text, fontSize: 27, fontWeight: '800', marginTop: spacing.sm }, metricLabel: { color: colors.muted, fontSize: 12, fontWeight: '600', marginTop: 2 },
  empty: { alignItems: 'center', padding: spacing.xl }, emptyIcon: { alignItems: 'center', backgroundColor: colors.tealDeep, borderRadius: 999, height: 46, justifyContent: 'center', marginBottom: spacing.md, width: 46 }, emptyTitle: { color: colors.text, fontSize: 16, fontWeight: '800' }, emptyMessage: { color: colors.muted, fontSize: 13, lineHeight: 19, marginTop: 6, textAlign: 'center' }, actionTile: { alignItems: 'center', backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 16, borderWidth: 1, flexDirection: 'row', minHeight: 68, padding: spacing.md }, actionIcon: { alignItems: 'center', backgroundColor: colors.tealDeep, borderRadius: 11, height: 38, justifyContent: 'center', width: 38 }, actionCopy: { flex: 1, marginLeft: spacing.md }, actionTitle: { color: colors.text, fontSize: 14, fontWeight: '800' }, actionSubtitle: { color: colors.muted, fontSize: 12, marginTop: 3 }, pressed: { opacity: 0.75 },
});